---
- name: config log-server
  hosts: log
  become: true
  roles:
    - journald_server
    - auditd_server

- name: web server
  hosts: web
  become: true
  roles: 
    - nginx
    - journald_client
    - auditd_client  
    - filebeat
