---

- name: config auditd server
  template:
    src: templates/auditd.conf
    dest: /etc/audit/auditd.conf
    owner: root
    group: root
    mode: "0640"

- name: restart auditd service
  command: service auditd restart
